### ISSUE TITLE
question: why forking the existing wink plugin?

### ISSUE THREAD

**Issue by keloin** [thechrisreese/Homebridge-winkv2#3]
Why not simply adding the feature to the original one? 
Are you planning to support this one? 

And then canary related question – the HomeKit app says the system is armed when the actual status is 'home'. Is it possible to change it so that is says its armed only when the status is, say, either 'away' or 'night'? 

Thanks for your work :-)

**Comment by thechrisreese** [comment]
Answers 

1) Because after requesting many times the original was not being updated. 

2) I will try to support but hey this is just my hack to make me happy and so far it works. 

3) Thatd a tough one because technically there are three versions of Armed - Armed Home, Armed Away, and Armed Night. There could be other ways, like only away or night are armed while others are disarmed, but I haven't really played with it.

**Comment by keloin** [comment]
Thanks man! I hear you. 
This made me happy too :-) So thanks again! 

Speaking about the last question – just went thru the apple documentation (https://developer.apple.com/reference/homekit/hmcharacteristicvaluecurrentsecuritysystemstate). Apparently there are not so many options. Armed Home will always be Armed first, and only then Home.
It looks like the only way is to map Armed Home (0) to Disarmed (3). Then Home.app will show it as disarmed. Dunno if this is a good way though. Its rather an evil hack, but I'll try it anyway.
I hope in future Apple will start displaying Armed Home better. 

Thanks!

**Comment by thechrisreese** [comment]
Bingo on the Armed home. I wasn't a big fan of Armed Home being Disarmed. 

I also haven't figured out Set yet. Still working on it but from what I can tell it's because Wink treats Canary as a camera for Get and something else for Set.

**Comment by keloin** [comment]
Hey, since the issue is still open, another question :-)
How do you make canary work as a motion sensor? Can you? 
Thanks!

**Comment by thechrisreese** [comment]
Sorry. I wish. That's a Wink issue. Wink sees it only as a camera. I have tried adding motion detection but it won't take because Canary only reports Armed status and not motion activity to wink.

**Comment by keloin** [comment]
:-( ok, this is sad. I was thinking about building some workflow that would turn the light on in the night when motion is detected. Would help me find the fridge in the darkness :-) 
Thanks anyways!

**Comment by thechrisreese** [comment]
Yeah ultimately I don't think the Canary is as great as my Ring Cams.

**Comment by thechrisreese** [comment]
OK - update through NPM

Changes - 

Now using node_module wink-jsv2. This is my own version. It has some breaking changes (no longer checks for if an update occurred) but will allow Canary to update. It also has a bunch of console.logs, sorry. 

Also this new version should do a better job with thermostats (at least for me). 

REMINDER - This is all about my system, so I hope it helps.

**Comment by thechrisreese** [comment]
next up - tackle V2 API

**Comment by keloin** [comment]
Installed v2 - it says:
`Error: The requested platform 'Wink' was not registered by any plugin.
`

Do I need to change the config file?

**Comment by thechrisreese** [comment]
Hmmm. 

 Give me more of the text from that error from the last time stamp

**Comment by thechrisreese** [comment]
An alternative may be that you did not install the Homebridge-winkV2 into the right directory? Do you use NVM or multiple versions of Node?

**Comment by keloin** [comment]
The single installation, the single everything – I have a special box to play with homebridge. 

Yeah, sorry, longer error stack proves that the problem is here: wink-jsV2.

Thanks! 


`[2/21/2017, 8:55:14 AM] ====================
[2/21/2017, 8:55:14 AM] ERROR LOADING PLUGIN homebridge-winkv2:
[2/21/2017, 8:55:14 AM] Error: Cannot find module 'wink-jsV2'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-winkv2/index.js:2:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
[2/21/2017, 8:55:14 AM] ====================
Error: The requested platform 'Wink' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
`

**Comment by thechrisreese** [comment]
Can you look in Homebridge-winkV2>Node_Modules> and see if Wink-jsV2 is there? It should have loaded but may need me to update Homebridge-winkv2 after a change I made yesterday.

**Comment by keloin** [comment]
Could the issue be in the naming? 
The module is installed - wink-jsv2@0.0.1
But the plugin is looking for wink-jsV2

**Comment by thechrisreese** [comment]
Ok I pushed a few changes. I doubt they will make a difference, but can you update Homebridge-winkv2 and check again? Post your console.log from the last time stamp if it fails.

**Comment by keloin** [comment]
yeah, the issue is with the naming :-)
I renamed js**v**2 to js**V**2 and everything started working perfectly.

**Comment by thechrisreese** [comment]
Which naming? The node_module? I was actively changing names last night and probably missed one/some.

**Comment by keloin** [comment]
You're referencing `wink-jsV2` somewhere in your `homebridge-winkv2`, while the actual name of the module is `wink-jsv2` (lowercase 'v'). 
I symlinked the folder like this:
`drwxr-xr-x  5 nobody ubuntu  4096 Feb 21 12:35 wink-jsv2/`
`lrwxrwxrwx  1 root   root       9 Feb 21 13:12 wink-jsV2 -> wink-jsv2/`
And then `homebridge-winkv2` successfully managed to find `wink-jsV2`.

Do you use case-sensitive filesystem?

**Comment by keloin** [comment]
Basically everywhere where you have `require('wink-jsV2');` you should have `require('wink-jsv2');` instead (lowercase 'v').

**Comment by thechrisreese** [comment]
I went through and scrubbed the Capitol V's and versioned up wink-jsv2. Apparently it is case sensitive but wasn't causing that issue on my end. 
Homebridge-winkv2 @2.0.0 and wink-jsv2 @0.0.2 should only have lowercase v's now. 

I pushed to Master about 2 minutes ago.

**Comment by keloin** [comment]
ok :-) i'll retry now

**Comment by thechrisreese** [comment]
Ok. Let me know if it works this time. I may need to push an NPM version update, but was avoiding that for this stuff.

**Comment by keloin** [comment]
looks like you do need to push a new version to npm ... 
deleted everything and installed from scratch – still the same issues

**Comment by thechrisreese** [comment]
I'll minor version it as soon as I can

**Comment by thechrisreese** [comment]
How about now? Should show Homebridge-winkv2 @2.0.1 and wink-jsv2@0.0.3

**Comment by keloin** [comment]
works beautifully!

**Comment by thechrisreese** [comment]
AWESOME I am going to close this for now.
